server:
  port: 8082

spring:
  application:
    name: events

  # Configuración de seguridad para OAuth2 Resource Server
  security:
    oauth2:
      resourceserver:
        jwt:
          # URL del emisor de tokens del User Pool de AWS Cognito de prueba
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_yzwNALI2A
